import {Store} from './store';

export const Coolmod: Store = {
  currency: '€',
  labels: {
    inStock: {
      container: '#product > div > div > div > button',
      text: ['Añadir a la cesta'],
    },
    maxPrice: {
      container: '#normalpricenumber',
      euroFormat: true,
    },
    outOfStock: {
      container: '#productBuyButtons',
      text: ['NO DISPONIBLE'],
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.coolmod.com/powercolor-radeon-rx-7900-xtx-hell-hound-oc-24gb-gddr6/',
    },
    {
      brand: 'amd',
      model: '5600x',
      series: 'ryzen5600',
      url: 'https://www.coolmod.com/amd-ryzen-5-5600x-46ghz-socket-am4-boxed-procesador-precio',
    },
    {
      brand: 'amd',
      model: '5800x',
      series: 'ryzen5800',
      url: 'https://www.coolmod.com/amd-ryzen-7-5800x-47ghz-socket-am4-boxed-procesador-precio',
    },
    {
      brand: 'amd',
      model: '5900x',
      series: 'ryzen5900',
      url: 'https://www.coolmod.com/amd-ryzen-9-5900x-48ghz-socket-am4-boxed-procesador-precio',
    },
    {
      brand: 'amd',
      model: '5950x',
      series: 'ryzen5950',
      url: 'https://www.coolmod.com/amd-ryzen-9-5950x-49ghz-socket-am4-boxed-procesador-precio',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '5090',
      url: 'https://www.coolmod.com/gigabyte-aorus-geforce-rtx-5090-xtreme-waterforce-wb-32gb-gddr7/',
    },
    {
      brand: 'gigabyte',
      model: 'rog astral',
      series: '5090',
      url: 'https://www.coolmod.com/asus-rog-astral-geforce-rtx-5090-gaming-32gb-gddr7/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce',
      series: '5090',
      url: 'https://www.coolmod.com/gigabyte-aorus-geforce-rtx-5090-xtreme-waterforce-32gb-gddr7/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master ice',
      series: '5090',
      url: 'https://www.coolmod.com/gigabyte-aorus-geforce-rtx-5090-master-ice-32gb-gddr7/',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '5090',
      url: 'https://www.coolmod.com/msi-geforce-rtx-5090-ventus-3x-oc-32gb-gddr7/',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '5090',
      url: 'https://www.coolmod.com/asus-tuf-gaming-geforce-rtx-5090-32gb-gddr7/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '5090',
      url: 'https://www.coolmod.com/gigabyte-aorus-geforce-rtx-5090-master-32gb-gddr7/',
    },
    {
      brand: 'gigabyte',
      model: 'windforce oc',
      series: '5090',
      url: 'https://www.coolmod.com/gigabyte-geforce-rtx-5090-windforce-oc-32gb-gddr7/',
    },
    {
      brand: 'gigabyte',
      model: 'oc',
      series: '5090',
      url: 'https://www.coolmod.com/gigabyte-geforce-rtx-5090-gaming-oc-32gb-gddr7/',
    },
    {
      brand: 'inno3d',
      model: 'x3',
      series: '5090',
      url: 'https://www.coolmod.com/inno3d-geforce-rtx-5090-x3-32gb-gddr7/',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3',
      series: '5090',
      url: 'https://www.coolmod.com/inno3d-geforce-rtx-5090-ichill-x3-32gb-gddr7/',
    },
    {
      brand: 'inno3d',
      model: 'ichill frostbite',
      series: '5090',
      url: 'https://www.coolmod.com/inno3d-geforce-rtx-5090-ichill-frostbite-32gb-gddr7/',
    },
    {
      brand: 'msi',
      model: 'suprim soc',
      series: '5090',
      url: 'https://www.coolmod.com/msi-geforce-rtx-5090-suprim-soc-32gb-gddr7/',
    },
    {
      brand: 'zotac',
      model: 'solid',
      series: '5090',
      url: 'https://www.coolmod.com/zotac-gaming-geforce-rtx-5090-solid-32gb-gddr7/',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '5090',
      url: 'https://www.coolmod.com/asus-tuf-gaming-geforce-rtx-5090-oc-32gb-gddr7/',
    },
    {
      brand: 'asus',
      model: 'rog astral',
      series: '5090',
      url: 'https://www.coolmod.com/asus-rog-astral-lc-geforce-rtx-5090-oc-gaming-32gb-gddr7/',
    },
    {
      brand: 'asus',
      model: 'rog astral',
      series: '5090',
      url: 'https://www.coolmod.com/asus-rog-astral-lc-geforce-rtx-5090-gaming-32gb-gddr7/',
    },
    {
      brand: 'asus',
      model: 'rog astral',
      series: '5090',
      url: 'https://www.coolmod.com/asus-rog-astral-geforce-rtx-5090-oc-gaming-32gb-gddr7/',
    },
    {
      brand: 'zotac',
      model: 'amp extreme infinity',
      series: '5090',
      url: 'https://www.coolmod.com/zotac-gaming-geforce-rtx-5090-amp-extreme-infinity-32gb-gddr7/',
    },
    {
      brand: 'zotac',
      model: 'solid oc',
      series: '5090',
      url: 'https://www.coolmod.com/zotac-gaming-geforce-rtx-5090-solid-oc-32gb-gddr7/',
    },
    {
      brand: 'msi',
      model: 'gaming trio',
      series: '5090',
      url: 'https://www.coolmod.com/msi-geforce-rtx-5090-gaming-trio-oc-32gb-gddr7/',
    },
    {
      brand: 'msi',
      model: 'suprim liquid soc',
      series: '5090',
      url: 'https://www.coolmod.com/msi-geforce-rtx-5090-suprim-liquid-soc-32gb-gddr7/',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '5090',
      url: 'https://www.coolmod.com/msi-geforce-rtx-5090-ventus-3x-oc-32gb-gddr7/',
    },
  ],
  name: 'coolmod',
};
